name: matomo_tracker
description: A fully cross-platform wrap of the Matomo tracking client for
  Flutter, using the Matomo API.
version: 4.0.0-dev.2
homepage: https://github.com/Floating-Dartists/matomo-tracker
repository: https://github.com/Floating-Dartists/matomo-tracker
issue_tracker: https://github.com/Floating-Dartists/matomo-tracker/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  clock: ^1.1.1
  collection: ^1.17.1
  device_info_plus: ^9.0.2
  flutter:
    sdk: flutter
  http: ^1.0.0
  package_info_plus: ^4.0.2
  shared_preferences: ^2.1.1
  uuid: ^3.0.7

dev_dependencies:
  fd_lints: ^1.1.1
  flutter_test:
    sdk: flutter
  meta: ^1.9.1
  mocktail: ^0.3.0

flutter: null
